### ISSUE TITLE
Game crashing and occasional shade polygons error. Log Below.

### ISSUE THREAD

**Issue by zetsuya** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#27] opened 2019-11-21 22:38 UTC
I hope I can be of any help to fix these issues.

[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/3877090/DS3PWLog.txt)

**Comment by turtlshell** [comment] 2019-11-25 01:38
polygons error is a dupe of #24 but the other access violation crash isn't

**Comment by LukeYui** [comment] 2019-11-25 07:39
Hello, thanks for the report. The access violation crash is the same as #25 and has been fixed, it'll be patched in the next update.

**Comment by zetsuya** [comment] 2019-11-25 13:55
> Hello, thanks for the report. The access violation crash is the same as #25 and has been fixed, it'll be patched in the next update.

About shade polygons, I've stopped receiving them after I stopped using MSI Afterburner, it it helps in any way.

**Comment by turtlshell** [comment] 2019-11-25 15:02
I've had the unable to shade polygons error with and without a GPU overclock, and since I'm on Linux I don't use MSI Afterburner so I doubt that's the issue.
That issue happens really sporadically for me so you might have just gotten lucky or something, not sure.

**Closed** 2020-04-23 15:58 UTC
