### ISSUE TITLE
Random crash report and arena connectivity issues

### ISSUE THREAD

**Issue by GuyFromYharnam** [Jellybaby34/Dark-Souls-3-PvP-Watchdog#32] opened 2020-02-18 21:00 UTC
I happened to me 2 or 3 times with an error message : [DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/4221641/DS3PWLog.txt)
BTW, i have also many issues to connect with people in the arena.

**Comment by UkrainianCitizen** [comment] 2020-03-28 18:59
I tend to crash as well during lengthy pvp sessions(typically when I invade) and typically several phantoms are involved. Happened at least 3 times during 2 days. The errors in the logs are identical to yours.
[DS3PWLog.txt](https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/files/4397694/DS3PWLog.txt)

**Comment by UkrainianCitizen** [comment] 2020-03-28 19:05
Duplicate of https://github.com/Jellybaby34/Dark-Souls-3-PvP-Watchdog/issues/29#

**Comment by LukeYui** [comment] 2020-04-23 00:23
Seeing as this issue should be resolved in the latest update, I'll close it for now.

**Closed by LukeYui** 2020-04-23 00:23 UTC
